# Generated by Django 4.0.3 on 2022-12-10 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recharge_plans', '0003_alter_plans_netowrk_operator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='recharge_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('recharged_status', models.CharField(choices=[('Processing', 'PROCESSING'), ('Success', 'SUCCESS'), ('Failed', 'FAILED')], max_length=30)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recharge_plans.plans')),
                ('recharged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
