# Generated by Django 4.0.3 on 2022-12-11 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recharge_record',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
