# Generated by Django 4.0.3 on 2022-12-10 19:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(150000), django.core.validators.MinValueValidator(0)])),
                ('wallet_adress', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('wallet_created_on', models.DateTimeField(auto_now_add=True)),
                ('Wallet_of', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
