# Generated by Django 4.0.3 on 2022-12-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
