# Generated by Django 4.0.3 on 2022-12-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharge_plans', '0003_alter_plans_netowrk_operator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plans',
            name='Netowrk_operator',
            field=models.CharField(choices=[('Airtel', 'AIRTEL'), ('Jio', 'JIO'), ('Idea', 'IDEA'), ('Vodafone', 'VODAFONE'), ('Bsnl', 'BSNL')], max_length=30),
        ),
    ]
